# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'node-exporter-ria-monitoring'
    ec2_sd_configs:
      - region: us-east-1
        profile: arn:aws:iam::102954369745:instance-profile/product-manual-ec2-role
        port: 9100
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Project]
        regex: RIA-*
        action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_tag_Name,__meta_ec2_availability_zone]
        target_label: instance

  - job_name: 'ria-app'
    metrics_path: '/metrics'
    scrape_interval: 20s
    static_configs:
    - targets: ['54.146.75.11:5000']